### ISSUE TITLE
Searches pull all parts

### ISSUE THREAD

**Issue by jagauthier** [Part-DB/Part-DB-symfony#165] opened 2022-08-08 17:51 UTC
I just did a new pull (docker, actually) and discovered that any and all searches always return all parts.

![image](https://user-images.githubusercontent.com/7101432/183481723-6379b57c-3eba-4aec-8b66-006081ec2045.png)

**Comment by jbtronics** [comment] 2022-08-13 20:53
That is not related to this issue, but you should really clear your browser cache. The formatting seems very wrong, which is most likely caused by some style mixup. Clearing browser cache should fix that

**Comment by jbtronics** [comment] 2022-08-13 21:07
Fixed now.

**Closed by jbtronics** 2022-08-13 21:07 UTC
Labels: bug

**Comment by jagauthier** [comment] 2022-08-15 15:41
Browser only did the weird search bar the one time. And thanks for fixing!
