### ISSUE TITLE
405 HTTP error on part deletion.

### ISSUE THREAD

**Issue by nskartem** [Part-DB/Part-DB-symfony#146] opened 2022-05-16 08:34 UTC
Hello!

When I'm trying to delete part, I'm getting the "No route found for "POST http://domain.com/en/part/6/delete": Method Not Allowed (Allow: DELETE)" error.

1. Try to delete any part from */part/*/info
2. Get error screen with: "No route found for "POST http://domain.com/en/part/6/delete": Method Not Allowed (Allow: DELETE)"

**Expected behavior**
Part deleted.

**Server Side**
- Part-DB Version: master image from Dockerhub (hash sha256:b0f144ae4a7f8412a8525e509875dade70ed8f786ca7e427ded06b571c2f049d)
- PHP Version: 7.4.29
- Database Server: SQLite

**Additional context**
Maybe it's bounded with issue #136, and it's broken after I tried jpg upload, but I deleted all the jpg attachments and restarted the container, so I don't think so. Possible apache2 configuration bug?

**Comment by jbtronics** [comment] 2022-07-21 22:36
Should be fixed now in the latest version.

**Comment by virtadpt** [comment] 2022-07-21 23:17
I just updated my install to the latest Git commit, and it's still returning HTTP 405's.

**Comment by jbtronics** [comment] 2022-07-21 23:26
Have you installed the new composer dependencies and done a `php bin/console cache:clear` after pulling the latest git commit?

**Comment by nskartem** [comment] 2022-07-22 09:04
Hello, @jbtronics!

Thanks for the fix, I'm using Docker image, which is built from this repo's Dockerfile (I'm running PartDB on a aarch64 server now, so I can't use dockerhub images). I've done git pull from master and rebuilt image, now deletion is working right:
![part-delete-success](https://user-images.githubusercontent.com/5293544/180404504-5d5eaae4-2d82-47f9-9b2d-dd7022f48716.png)
Thank you!

**Comment by jbtronics** [comment] 2022-07-22 09:11
Maybe as a sidenote: In Principle the GitHub action i use to automatically build the Docker images can build images for other platform too (including several ARM architectures).

The problem is that as these other architectures has to be emulated via QEMU, this is very slow (and not reasonable to do for every commit). When there will be tagged  releases of Part-DB, however I plan to include images for other architectures than amd64 too.

**Comment by nskartem** [comment] 2022-07-22 09:42
By the way, if you need some help with automation/build/pipelines/etc. (without coding), I'd like to help you, because it'll be interesting to support such a great open source project. I work in a middle-sized company as an outsource Linux administrator/DevOps.

**Comment by virtadpt** [comment] 2022-07-22 17:48
@jbtronics Yes, I have.

**Comment by virtadpt** [comment] 2022-08-01 20:30
Updated to master/a8bd894.  Able to delete parts now but that's about it.

**Comment by jbtronics** [comment] 2023-02-06 20:33
Should be fixed some time ago.

**Closed by jbtronics** 2023-02-06 20:33 UTC
Labels: bug
